# Generated by Django 3.0.5 on 2020-05-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTrucks',
            new_name='FoodTruck',
        ),
    ]
