# Generated by Django 3.0.5 on 2020-05-10 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0003_auto_20200510_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
