# Generated by Django 3.0.5 on 2020-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('foodtrucks', '0004_auto_20200510_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
