# Generated by Django 3.0.5 on 2020-05-10 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('foodtrucks', '0005_auto_20200510_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
